import { all, call, put, select, takeLatest } from "typed-redux-saga";
import axios from "axios";

import { RootState } from "../redux/rootReducer";
import { weatherSlice } from "../redux/slices/weather";

function* onLoadCurrentLocationForecast() {
   yield* put(weatherSlice.actions.setCurrentLocationForecast(undefined));

   const currentLocation = yield* call(
      (): Promise<{
         lat: number;
         lon: number;
      }> =>
         new Promise((resolve) =>
            navigator.geolocation.getCurrentPosition(
               (position) =>
                  resolve({
                     lat: position.coords.latitude,
                     lon: position.coords.longitude,
                  }),
               () =>
                  resolve({
                     lat: 0,
                     lon: 0,
                  }),
            ),
         ),
   );

   const units = yield* select((state: RootState) => state.app.unit);
   const currentLocationName = yield* select(
      (state: RootState) => state.weather.currentLocation?.name,
   );

   try {
      if (!currentLocationName) {
         const currentLocationWeather = yield* call(() =>
            axios.get("https://api.openweathermap.org/data/2.5/weather", {
               params: {
                  lat: currentLocation.lat,
                  lon: currentLocation.lon,
                  units,
                  appid: "e2e28b1afeef6701c57c2d269329f53d",
               },
            }),
         );
         // const currentLocationWeather = {
         //    data: {
         //       name: "Knyazhevo",
         //    },
         // };

         yield* put(
            weatherSlice.actions.setCurrentLocationName(currentLocationWeather.data.name),
         );
      }

      const currentLocationWeatherOneCall = yield* call(() =>
         axios.get("https://api.openweathermap.org/data/3.0/onecall", {
            params: {
               lat: currentLocation.lat,
               lon: currentLocation.lon,
               units,
               exclude: "minutely,alerts",
               appid: "e2e28b1afeef6701c57c2d269329f53d",
            },
         }),
      );
      // const currentLocationWeatherOneCall = {
      //    data: {
      //       lat: 42.6855,
      //       lon: 23.265,
      //       timezone: "Europe/Sofia",
      //       timezone_offset: 10800,
      //       current: {
      //          dt: 1696365173,
      //          sunrise: 1696307136,
      //          sunset: 1696349188,
      //          temp: 11.65,
      //          feels_like: 10.59,
      //          pressure: 1025,
      //          humidity: 66,
      //          dew_point: 5.52,
      //          uvi: 0,
      //          clouds: 29,
      //          visibility: 10000,
      //          wind_speed: 3.09,
      //          wind_deg: 140,
      //          weather: [
      //             {
      //                id: 802,
      //                main: "Clouds",
      //                description: "scattered clouds",
      //                icon: "03n",
      //             },
      //          ],
      //       },
      //       hourly: [
      //          {
      //             dt: 1696363200,
      //             temp: 12.24,
      //             feels_like: 11.16,
      //             pressure: 1025,
      //             humidity: 63,
      //             dew_point: 5.41,
      //             uvi: 0,
      //             clouds: 31,
      //             visibility: 10000,
      //             wind_speed: 0.79,
      //             wind_deg: 99,
      //             wind_gust: 0.99,
      //             weather: [
      //                {
      //                   id: 802,
      //                   main: "Clouds",
      //                   description: "scattered clouds",
      //                   icon: "03n",
      //                },
      //             ],
      //             pop: 0,
      //          },
      //          {
      //             dt: 1696366800,
      //             temp: 11.65,
      //             feels_like: 10.59,
      //             pressure: 1025,
      //             humidity: 66,
      //             dew_point: 5.52,
      //             uvi: 0,
      //             clouds: 29,
      //             visibility: 10000,
      //             wind_speed: 0.59,
      //             wind_deg: 106,
      //             wind_gust: 0.83,
      //             weather: [
      //                {
      //                   id: 802,
      //                   main: "Clouds",
      //                   description: "scattered clouds",
      //                   icon: "03n",
      //                },
      //             ],
      //             pop: 0,
      //          },
      //          {
      //             dt: 1696370400,
      //             temp: 12,
      //             feels_like: 10.93,
      //             pressure: 1025,
      //             humidity: 64,
      //             dew_point: 5.41,
      //             uvi: 0,
      //             clouds: 28,
      //             visibility: 10000,
      //             wind_speed: 0.55,
      //             wind_deg: 116,
      //             wind_gust: 0.81,
      //             weather: [
      //                {
      //                   id: 802,
      //                   main: "Clouds",
      //                   description: "scattered clouds",
      //                   icon: "03n",
      //                },
      //             ],
      //             pop: 0,
      //          },
      //          {
      //             dt: 1696374000,
      //             temp: 12.19,
      //             feels_like: 11.11,
      //             pressure: 1025,
      //             humidity: 63,
      //             dew_point: 5.36,
      //             uvi: 0,
      //             clouds: 25,
      //             visibility: 10000,
      //             wind_speed: 0.49,
      //             wind_deg: 114,
      //             wind_gust: 0.71,
      //             weather: [
      //                {
      //                   id: 802,
      //                   main: "Clouds",
      //                   description: "scattered clouds",
      //                   icon: "03n",
      //                },
      //             ],
      //             pop: 0,
      //          },
      //          {
      //             dt: 1696377600,
      //             temp: 12.2,
      //             feels_like: 11.12,
      //             pressure: 1025,
      //             humidity: 63,
      //             dew_point: 5.37,
      //             uvi: 0,
      //             clouds: 21,
      //             visibility: 10000,
      //             wind_speed: 0.21,
      //             wind_deg: 118,
      //             wind_gust: 0.61,
      //             weather: [
      //                {
      //                   id: 801,
      //                   main: "Clouds",
      //                   description: "few clouds",
      //                   icon: "02n",
      //                },
      //             ],
      //             pop: 0,
      //          },
      //          {
      //             dt: 1696381200,
      //             temp: 12.07,
      //             feels_like: 10.95,
      //             pressure: 1024,
      //             humidity: 62,
      //             dew_point: 5.02,
      //             uvi: 0,
      //             clouds: 6,
      //             visibility: 10000,
      //             wind_speed: 0.2,
      //             wind_deg: 270,
      //             wind_gust: 0.66,
      //             weather: [
      //                {
      //                   id: 800,
      //                   main: "Clear",
      //                   description: "clear sky",
      //                   icon: "01n",
      //                },
      //             ],
      //             pop: 0,
      //          },
      //          {
      //             dt: 1696384800,
      //             temp: 11.77,
      //             feels_like: 10.67,
      //             pressure: 1024,
      //             humidity: 64,
      //             dew_point: 4.45,
      //             uvi: 0,
      //             clouds: 0,
      //             visibility: 10000,
      //             wind_speed: 0.28,
      //             wind_deg: 251,
      //             wind_gust: 0.56,
      //             weather: [
      //                {
      //                   id: 800,
      //                   main: "Clear",
      //                   description: "clear sky",
      //                   icon: "01n",
      //                },
      //             ],
      //             pop: 0,
      //          },
      //          {
      //             dt: 1696388400,
      //             temp: 11.49,
      //             feels_like: 10.39,
      //             pressure: 1024,
      //             humidity: 65,
      //             dew_point: 4.46,
      //             uvi: 0,
      //             clouds: 0,
      //             visibility: 10000,
      //             wind_speed: 0.23,
      //             wind_deg: 195,
      //             wind_gust: 0.52,
      //             weather: [
      //                {
      //                   id: 800,
      //                   main: "Clear",
      //                   description: "clear sky",
      //                   icon: "01n",
      //                },
      //             ],
      //             pop: 0,
      //          },
      //          {
      //             dt: 1696392000,
      //             temp: 11.17,
      //             feels_like: 10.07,
      //             pressure: 1024,
      //             humidity: 66,
      //             dew_point: 4.37,
      //             uvi: 0,
      //             clouds: 0,
      //             visibility: 10000,
      //             wind_speed: 0.26,
      //             wind_deg: 180,
      //             wind_gust: 0.53,
      //             weather: [
      //                {
      //                   id: 800,
      //                   main: "Clear",
      //                   description: "clear sky",
      //                   icon: "01n",
      //                },
      //             ],
      //             pop: 0,
      //          },
      //          {
      //             dt: 1696395600,
      //             temp: 11.62,
      //             feels_like: 10.51,
      //             pressure: 1025,
      //             humidity: 64,
      //             dew_point: 4.43,
      //             uvi: 0,
      //             clouds: 0,
      //             visibility: 10000,
      //             wind_speed: 0.19,
      //             wind_deg: 227,
      //             wind_gust: 0.47,
      //             weather: [
      //                {
      //                   id: 800,
      //                   main: "Clear",
      //                   description: "clear sky",
      //                   icon: "01d",
      //                },
      //             ],
      //             pop: 0,
      //          },
      //          {
      //             dt: 1696399200,
      //             temp: 14.07,
      //             feels_like: 12.97,
      //             pressure: 1025,
      //             humidity: 55,
      //             dew_point: 4.51,
      //             uvi: 0.44,
      //             clouds: 0,
      //             visibility: 10000,
      //             wind_speed: 0.46,
      //             wind_deg: 302,
      //             wind_gust: 0.87,
      //             weather: [
      //                {
      //                   id: 800,
      //                   main: "Clear",
      //                   description: "clear sky",
      //                   icon: "01d",
      //                },
      //             ],
      //             pop: 0,
      //          },
      //          {
      //             dt: 1696402800,
      //             temp: 16.66,
      //             feels_like: 15.58,
      //             pressure: 1025,
      //             humidity: 46,
      //             dew_point: 4.63,
      //             uvi: 1.34,
      //             clouds: 0,
      //             visibility: 10000,
      //             wind_speed: 0.9,
      //             wind_deg: 299,
      //             wind_gust: 1.22,
      //             weather: [
      //                {
      //                   id: 800,
      //                   main: "Clear",
      //                   description: "clear sky",
      //                   icon: "01d",
      //                },
      //             ],
      //             pop: 0,
      //          },
      //          {
      //             dt: 1696406400,
      //             temp: 19.39,
      //             feels_like: 18.4,
      //             pressure: 1024,
      //             humidity: 39,
      //             dew_point: 4.44,
      //             uvi: 2.68,
      //             clouds: 0,
      //             visibility: 10000,
      //             wind_speed: 0.86,
      //             wind_deg: 281,
      //             wind_gust: 1.43,
      //             weather: [
      //                {
      //                   id: 800,
      //                   main: "Clear",
      //                   description: "clear sky",
      //                   icon: "01d",
      //                },
      //             ],
      //             pop: 0,
      //          },
      //          {
      //             dt: 1696410000,
      //             temp: 21.51,
      //             feels_like: 20.58,
      //             pressure: 1023,
      //             humidity: 33,
      //             dew_point: 4.21,
      //             uvi: 4.04,
      //             clouds: 0,
      //             visibility: 10000,
      //             wind_speed: 1.45,
      //             wind_deg: 302,
      //             wind_gust: 2.09,
      //             weather: [
      //                {
      //                   id: 800,
      //                   main: "Clear",
      //                   description: "clear sky",
      //                   icon: "01d",
      //                },
      //             ],
      //             pop: 0,
      //          },
      //          {
      //             dt: 1696413600,
      //             temp: 23.34,
      //             feels_like: 22.49,
      //             pressure: 1023,
      //             humidity: 29,
      //             dew_point: 3.95,
      //             uvi: 4.79,
      //             clouds: 0,
      //             visibility: 10000,
      //             wind_speed: 1.66,
      //             wind_deg: 323,
      //             wind_gust: 2.14,
      //             weather: [
      //                {
      //                   id: 800,
      //                   main: "Clear",
      //                   description: "clear sky",
      //                   icon: "01d",
      //                },
      //             ],
      //             pop: 0,
      //          },
      //          {
      //             dt: 1696417200,
      //             temp: 24.58,
      //             feels_like: 23.77,
      //             pressure: 1022,
      //             humidity: 26,
      //             dew_point: 3.61,
      //             uvi: 4.75,
      //             clouds: 1,
      //             visibility: 10000,
      //             wind_speed: 1.14,
      //             wind_deg: 343,
      //             wind_gust: 1.8,
      //             weather: [
      //                {
      //                   id: 800,
      //                   main: "Clear",
      //                   description: "clear sky",
      //                   icon: "01d",
      //                },
      //             ],
      //             pop: 0,
      //          },
      //          {
      //             dt: 1696420800,
      //             temp: 25.19,
      //             feels_like: 24.42,
      //             pressure: 1022,
      //             humidity: 25,
      //             dew_point: 3.46,
      //             uvi: 3.89,
      //             clouds: 3,
      //             visibility: 10000,
      //             wind_speed: 0.27,
      //             wind_deg: 358,
      //             wind_gust: 1.82,
      //             weather: [
      //                {
      //                   id: 800,
      //                   main: "Clear",
      //                   description: "clear sky",
      //                   icon: "01d",
      //                },
      //             ],
      //             pop: 0,
      //          },
      //          {
      //             dt: 1696424400,
      //             temp: 25.46,
      //             feels_like: 24.71,
      //             pressure: 1021,
      //             humidity: 25,
      //             dew_point: 3.4,
      //             uvi: 2.53,
      //             clouds: 13,
      //             visibility: 10000,
      //             wind_speed: 0.34,
      //             wind_deg: 157,
      //             wind_gust: 2.11,
      //             weather: [
      //                {
      //                   id: 801,
      //                   main: "Clouds",
      //                   description: "few clouds",
      //                   icon: "02d",
      //                },
      //             ],
      //             pop: 0,
      //          },
      //          {
      //             dt: 1696428000,
      //             temp: 25.19,
      //             feels_like: 24.42,
      //             pressure: 1021,
      //             humidity: 25,
      //             dew_point: 3.38,
      //             uvi: 1.25,
      //             clouds: 37,
      //             visibility: 10000,
      //             wind_speed: 0.52,
      //             wind_deg: 170,
      //             wind_gust: 1.9,
      //             weather: [
      //                {
      //                   id: 802,
      //                   main: "Clouds",
      //                   description: "scattered clouds",
      //                   icon: "03d",
      //                },
      //             ],
      //             pop: 0,
      //          },
      //          {
      //             dt: 1696431600,
      //             temp: 24.17,
      //             feels_like: 23.37,
      //             pressure: 1021,
      //             humidity: 28,
      //             dew_point: 4.16,
      //             uvi: 0.39,
      //             clouds: 31,
      //             visibility: 10000,
      //             wind_speed: 0.74,
      //             wind_deg: 144,
      //             wind_gust: 1.15,
      //             weather: [
      //                {
      //                   id: 802,
      //                   main: "Clouds",
      //                   description: "scattered clouds",
      //                   icon: "03d",
      //                },
      //             ],
      //             pop: 0,
      //          },
      //          {
      //             dt: 1696435200,
      //             temp: 20.65,
      //             feels_like: 19.66,
      //             pressure: 1022,
      //             humidity: 34,
      //             dew_point: 3.86,
      //             uvi: 0,
      //             clouds: 25,
      //             visibility: 10000,
      //             wind_speed: 1.25,
      //             wind_deg: 79,
      //             wind_gust: 1.28,
      //             weather: [
      //                {
      //                   id: 802,
      //                   main: "Clouds",
      //                   description: "scattered clouds",
      //                   icon: "03d",
      //                },
      //             ],
      //             pop: 0,
      //          },
      //          {
      //             dt: 1696438800,
      //             temp: 18.71,
      //             feels_like: 17.65,
      //             pressure: 1023,
      //             humidity: 39,
      //             dew_point: 4.07,
      //             uvi: 0,
      //             clouds: 21,
      //             visibility: 10000,
      //             wind_speed: 1.3,
      //             wind_deg: 49,
      //             wind_gust: 1.31,
      //             weather: [
      //                {
      //                   id: 801,
      //                   main: "Clouds",
      //                   description: "few clouds",
      //                   icon: "02n",
      //                },
      //             ],
      //             pop: 0,
      //          },
      //          {
      //             dt: 1696442400,
      //             temp: 17.66,
      //             feels_like: 16.58,
      //             pressure: 1023,
      //             humidity: 42,
      //             dew_point: 4.24,
      //             uvi: 0,
      //             clouds: 19,
      //             visibility: 10000,
      //             wind_speed: 0.82,
      //             wind_deg: 27,
      //             wind_gust: 0.8,
      //             weather: [
      //                {
      //                   id: 801,
      //                   main: "Clouds",
      //                   description: "few clouds",
      //                   icon: "02n",
      //                },
      //             ],
      //             pop: 0,
      //          },
      //          {
      //             dt: 1696446000,
      //             temp: 17.05,
      //             feels_like: 15.96,
      //             pressure: 1024,
      //             humidity: 44,
      //             dew_point: 4.31,
      //             uvi: 0,
      //             clouds: 19,
      //             visibility: 10000,
      //             wind_speed: 0.49,
      //             wind_deg: 23,
      //             wind_gust: 0.58,
      //             weather: [
      //                {
      //                   id: 801,
      //                   main: "Clouds",
      //                   description: "few clouds",
      //                   icon: "02n",
      //                },
      //             ],
      //             pop: 0,
      //          },
      //          {
      //             dt: 1696449600,
      //             temp: 16.47,
      //             feels_like: 15.37,
      //             pressure: 1024,
      //             humidity: 46,
      //             dew_point: 4.39,
      //             uvi: 0,
      //             clouds: 23,
      //             visibility: 10000,
      //             wind_speed: 0.62,
      //             wind_deg: 354,
      //             wind_gust: 0.75,
      //             weather: [
      //                {
      //                   id: 801,
      //                   main: "Clouds",
      //                   description: "few clouds",
      //                   icon: "02n",
      //                },
      //             ],
      //             pop: 0,
      //          },
      //          {
      //             dt: 1696453200,
      //             temp: 16.01,
      //             feels_like: 14.92,
      //             pressure: 1024,
      //             humidity: 48,
      //             dew_point: 4.64,
      //             uvi: 0,
      //             clouds: 45,
      //             visibility: 10000,
      //             wind_speed: 0.71,
      //             wind_deg: 340,
      //             wind_gust: 0.78,
      //             weather: [
      //                {
      //                   id: 802,
      //                   main: "Clouds",
      //                   description: "scattered clouds",
      //                   icon: "03n",
      //                },
      //             ],
      //             pop: 0,
      //          },
      //          {
      //             dt: 1696456800,
      //             temp: 15.48,
      //             feels_like: 14.42,
      //             pressure: 1024,
      //             humidity: 51,
      //             dew_point: 4.77,
      //             uvi: 0,
      //             clouds: 56,
      //             visibility: 10000,
      //             wind_speed: 0.49,
      //             wind_deg: 317,
      //             wind_gust: 0.71,
      //             weather: [
      //                {
      //                   id: 803,
      //                   main: "Clouds",
      //                   description: "broken clouds",
      //                   icon: "04n",
      //                },
      //             ],
      //             pop: 0,
      //          },
      //          {
      //             dt: 1696460400,
      //             temp: 14.98,
      //             feels_like: 13.92,
      //             pressure: 1024,
      //             humidity: 53,
      //             dew_point: 4.89,
      //             uvi: 0,
      //             clouds: 51,
      //             visibility: 10000,
      //             wind_speed: 0.52,
      //             wind_deg: 299,
      //             wind_gust: 0.84,
      //             weather: [
      //                {
      //                   id: 803,
      //                   main: "Clouds",
      //                   description: "broken clouds",
      //                   icon: "04n",
      //                },
      //             ],
      //             pop: 0,
      //          },
      //          {
      //             dt: 1696464000,
      //             temp: 14.51,
      //             feels_like: 13.45,
      //             pressure: 1024,
      //             humidity: 55,
      //             dew_point: 5.25,
      //             uvi: 0,
      //             clouds: 48,
      //             visibility: 10000,
      //             wind_speed: 0.91,
      //             wind_deg: 306,
      //             wind_gust: 1.09,
      //             weather: [
      //                {
      //                   id: 802,
      //                   main: "Clouds",
      //                   description: "scattered clouds",
      //                   icon: "03n",
      //                },
      //             ],
      //             pop: 0,
      //          },
      //          {
      //             dt: 1696467600,
      //             temp: 14.3,
      //             feels_like: 13.3,
      //             pressure: 1024,
      //             humidity: 58,
      //             dew_point: 5.58,
      //             uvi: 0,
      //             clouds: 100,
      //             visibility: 10000,
      //             wind_speed: 0.85,
      //             wind_deg: 299,
      //             wind_gust: 1.23,
      //             weather: [
      //                {
      //                   id: 804,
      //                   main: "Clouds",
      //                   description: "overcast clouds",
      //                   icon: "04n",
      //                },
      //             ],
      //             pop: 0,
      //          },
      //          {
      //             dt: 1696471200,
      //             temp: 14.14,
      //             feels_like: 13.18,
      //             pressure: 1024,
      //             humidity: 60,
      //             dew_point: 6.02,
      //             uvi: 0,
      //             clouds: 100,
      //             visibility: 10000,
      //             wind_speed: 0.83,
      //             wind_deg: 289,
      //             wind_gust: 1.21,
      //             weather: [
      //                {
      //                   id: 804,
      //                   main: "Clouds",
      //                   description: "overcast clouds",
      //                   icon: "04n",
      //                },
      //             ],
      //             pop: 0,
      //          },
      //          {
      //             dt: 1696474800,
      //             temp: 13.95,
      //             feels_like: 13.05,
      //             pressure: 1024,
      //             humidity: 63,
      //             dew_point: 6.37,
      //             uvi: 0,
      //             clouds: 100,
      //             visibility: 10000,
      //             wind_speed: 0.84,
      //             wind_deg: 297,
      //             wind_gust: 1.24,
      //             weather: [
      //                {
      //                   id: 804,
      //                   main: "Clouds",
      //                   description: "overcast clouds",
      //                   icon: "04n",
      //                },
      //             ],
      //             pop: 0,
      //          },
      //          {
      //             dt: 1696478400,
      //             temp: 13.78,
      //             feels_like: 12.91,
      //             pressure: 1024,
      //             humidity: 65,
      //             dew_point: 6.78,
      //             uvi: 0,
      //             clouds: 100,
      //             visibility: 10000,
      //             wind_speed: 1.16,
      //             wind_deg: 305,
      //             wind_gust: 1.6,
      //             weather: [
      //                {
      //                   id: 804,
      //                   main: "Clouds",
      //                   description: "overcast clouds",
      //                   icon: "04n",
      //                },
      //             ],
      //             pop: 0,
      //          },
      //          {
      //             dt: 1696482000,
      //             temp: 14.13,
      //             feels_like: 13.32,
      //             pressure: 1025,
      //             humidity: 66,
      //             dew_point: 7.35,
      //             uvi: 0,
      //             clouds: 100,
      //             visibility: 10000,
      //             wind_speed: 1.34,
      //             wind_deg: 302,
      //             wind_gust: 1.96,
      //             weather: [
      //                {
      //                   id: 804,
      //                   main: "Clouds",
      //                   description: "overcast clouds",
      //                   icon: "04d",
      //                },
      //             ],
      //             pop: 0,
      //          },
      //          {
      //             dt: 1696485600,
      //             temp: 15.55,
      //             feels_like: 14.81,
      //             pressure: 1025,
      //             humidity: 63,
      //             dew_point: 7.88,
      //             uvi: 0.36,
      //             clouds: 100,
      //             visibility: 10000,
      //             wind_speed: 1.36,
      //             wind_deg: 299,
      //             wind_gust: 2.08,
      //             weather: [
      //                {
      //                   id: 804,
      //                   main: "Clouds",
      //                   description: "overcast clouds",
      //                   icon: "04d",
      //                },
      //             ],
      //             pop: 0,
      //          },
      //          {
      //             dt: 1696489200,
      //             temp: 17.71,
      //             feels_like: 16.97,
      //             pressure: 1025,
      //             humidity: 55,
      //             dew_point: 8.04,
      //             uvi: 1.14,
      //             clouds: 58,
      //             visibility: 10000,
      //             wind_speed: 1.58,
      //             wind_deg: 303,
      //             wind_gust: 1.79,
      //             weather: [
      //                {
      //                   id: 803,
      //                   main: "Clouds",
      //                   description: "broken clouds",
      //                   icon: "04d",
      //                },
      //             ],
      //             pop: 0,
      //          },
      //          {
      //             dt: 1696492800,
      //             temp: 19.89,
      //             feels_like: 19.19,
      //             pressure: 1024,
      //             humidity: 48,
      //             dew_point: 7.94,
      //             uvi: 2.27,
      //             clouds: 52,
      //             visibility: 10000,
      //             wind_speed: 1.33,
      //             wind_deg: 311,
      //             wind_gust: 1.11,
      //             weather: [
      //                {
      //                   id: 803,
      //                   main: "Clouds",
      //                   description: "broken clouds",
      //                   icon: "04d",
      //                },
      //             ],
      //             pop: 0,
      //          },
      //          {
      //             dt: 1696496400,
      //             temp: 21.76,
      //             feels_like: 21.09,
      //             pressure: 1024,
      //             humidity: 42,
      //             dew_point: 7.83,
      //             uvi: 3.43,
      //             clouds: 46,
      //             visibility: 10000,
      //             wind_speed: 1.14,
      //             wind_deg: 317,
      //             wind_gust: 0.89,
      //             weather: [
      //                {
      //                   id: 802,
      //                   main: "Clouds",
      //                   description: "scattered clouds",
      //                   icon: "03d",
      //                },
      //             ],
      //             pop: 0,
      //          },
      //          {
      //             dt: 1696500000,
      //             temp: 23.41,
      //             feels_like: 22.77,
      //             pressure: 1023,
      //             humidity: 37,
      //             dew_point: 7.6,
      //             uvi: 4.14,
      //             clouds: 37,
      //             visibility: 10000,
      //             wind_speed: 0.61,
      //             wind_deg: 336,
      //             wind_gust: 0.62,
      //             weather: [
      //                {
      //                   id: 802,
      //                   main: "Clouds",
      //                   description: "scattered clouds",
      //                   icon: "03d",
      //                },
      //             ],
      //             pop: 0,
      //          },
      //          {
      //             dt: 1696503600,
      //             temp: 24.08,
      //             feels_like: 23.46,
      //             pressure: 1022,
      //             humidity: 35,
      //             dew_point: 7.22,
      //             uvi: 4.11,
      //             clouds: 32,
      //             visibility: 10000,
      //             wind_speed: 1.47,
      //             wind_deg: 328,
      //             wind_gust: 1.45,
      //             weather: [
      //                {
      //                   id: 802,
      //                   main: "Clouds",
      //                   description: "scattered clouds",
      //                   icon: "03d",
      //                },
      //             ],
      //             pop: 0,
      //          },
      //          {
      //             dt: 1696507200,
      //             temp: 24.62,
      //             feels_like: 24,
      //             pressure: 1021,
      //             humidity: 33,
      //             dew_point: 6.74,
      //             uvi: 3.36,
      //             clouds: 30,
      //             visibility: 10000,
      //             wind_speed: 1.38,
      //             wind_deg: 325,
      //             wind_gust: 1.45,
      //             weather: [
      //                {
      //                   id: 802,
      //                   main: "Clouds",
      //                   description: "scattered clouds",
      //                   icon: "03d",
      //                },
      //             ],
      //             pop: 0,
      //          },
      //          {
      //             dt: 1696510800,
      //             temp: 24.66,
      //             feels_like: 24.02,
      //             pressure: 1021,
      //             humidity: 32,
      //             dew_point: 6.54,
      //             uvi: 1.91,
      //             clouds: 79,
      //             visibility: 10000,
      //             wind_speed: 1.45,
      //             wind_deg: 313,
      //             wind_gust: 1.56,
      //             weather: [
      //                {
      //                   id: 803,
      //                   main: "Clouds",
      //                   description: "broken clouds",
      //                   icon: "04d",
      //                },
      //             ],
      //             pop: 0,
      //          },
      //          {
      //             dt: 1696514400,
      //             temp: 24.17,
      //             feels_like: 23.5,
      //             pressure: 1020,
      //             humidity: 33,
      //             dew_point: 6.42,
      //             uvi: 0.94,
      //             clouds: 89,
      //             visibility: 10000,
      //             wind_speed: 1.55,
      //             wind_deg: 315,
      //             wind_gust: 1.55,
      //             weather: [
      //                {
      //                   id: 804,
      //                   main: "Clouds",
      //                   description: "overcast clouds",
      //                   icon: "04d",
      //                },
      //             ],
      //             pop: 0,
      //          },
      //          {
      //             dt: 1696518000,
      //             temp: 23.24,
      //             feels_like: 22.56,
      //             pressure: 1020,
      //             humidity: 36,
      //             dew_point: 6.87,
      //             uvi: 0.3,
      //             clouds: 93,
      //             visibility: 10000,
      //             wind_speed: 2.02,
      //             wind_deg: 323,
      //             wind_gust: 2.74,
      //             weather: [
      //                {
      //                   id: 804,
      //                   main: "Clouds",
      //                   description: "overcast clouds",
      //                   icon: "04d",
      //                },
      //             ],
      //             pop: 0,
      //          },
      //          {
      //             dt: 1696521600,
      //             temp: 20.52,
      //             feels_like: 19.72,
      //             pressure: 1021,
      //             humidity: 42,
      //             dew_point: 6.98,
      //             uvi: 0,
      //             clouds: 96,
      //             visibility: 10000,
      //             wind_speed: 2.29,
      //             wind_deg: 331,
      //             wind_gust: 3.65,
      //             weather: [
      //                {
      //                   id: 804,
      //                   main: "Clouds",
      //                   description: "overcast clouds",
      //                   icon: "04d",
      //                },
      //             ],
      //             pop: 0,
      //          },
      //          {
      //             dt: 1696525200,
      //             temp: 18.79,
      //             feels_like: 18,
      //             pressure: 1021,
      //             humidity: 49,
      //             dew_point: 7.39,
      //             uvi: 0,
      //             clouds: 77,
      //             visibility: 10000,
      //             wind_speed: 1.65,
      //             wind_deg: 348,
      //             wind_gust: 2.76,
      //             weather: [
      //                {
      //                   id: 803,
      //                   main: "Clouds",
      //                   description: "broken clouds",
      //                   icon: "04n",
      //                },
      //             ],
      //             pop: 0,
      //          },
      //          {
      //             dt: 1696528800,
      //             temp: 17.49,
      //             feels_like: 16.76,
      //             pressure: 1022,
      //             humidity: 56,
      //             dew_point: 8.01,
      //             uvi: 0,
      //             clouds: 64,
      //             visibility: 10000,
      //             wind_speed: 1.28,
      //             wind_deg: 360,
      //             wind_gust: 1.51,
      //             weather: [
      //                {
      //                   id: 803,
      //                   main: "Clouds",
      //                   description: "broken clouds",
      //                   icon: "04n",
      //                },
      //             ],
      //             pop: 0,
      //          },
      //          {
      //             dt: 1696532400,
      //             temp: 16.59,
      //             feels_like: 15.87,
      //             pressure: 1022,
      //             humidity: 60,
      //             dew_point: 8.34,
      //             uvi: 0,
      //             clouds: 0,
      //             visibility: 10000,
      //             wind_speed: 1.05,
      //             wind_deg: 360,
      //             wind_gust: 1.11,
      //             weather: [
      //                {
      //                   id: 800,
      //                   main: "Clear",
      //                   description: "clear sky",
      //                   icon: "01n",
      //                },
      //             ],
      //             pop: 0,
      //          },
      //       ],
      //       daily: [
      //          {
      //             dt: 1696327200,
      //             sunrise: 1696307136,
      //             sunset: 1696349188,
      //             moonrise: 1696357020,
      //             moonset: 1696324380,
      //             moon_phase: 0.65,
      //             summary:
      //                "You can expect clear sky in the morning, with partly cloudy in the afternoon",
      //             temp: {
      //                day: 20.73,
      //                min: 10.11,
      //                max: 22.55,
      //                night: 12.24,
      //                eve: 18.4,
      //                morn: 10.11,
      //             },
      //             feels_like: {
      //                day: 19.82,
      //                night: 11.16,
      //                eve: 17.31,
      //                morn: 9.13,
      //             },
      //             pressure: 1025,
      //             humidity: 37,
      //             dew_point: 4.96,
      //             wind_speed: 1.41,
      //             wind_deg: 11,
      //             wind_gust: 1.71,
      //             weather: [
      //                {
      //                   id: 800,
      //                   main: "Clear",
      //                   description: "clear sky",
      //                   icon: "01d",
      //                },
      //             ],
      //             clouds: 5,
      //             pop: 0,
      //             uvi: 4.77,
      //          },
      //          {
      //             dt: 1696413600,
      //             sunrise: 1696393602,
      //             sunset: 1696435482,
      //             moonrise: 1696445940,
      //             moonset: 1696415040,
      //             moon_phase: 0.68,
      //             summary: "Expect a day of partly cloudy with clear spells",
      //             temp: {
      //                day: 23.34,
      //                min: 11.17,
      //                max: 25.46,
      //                night: 16.47,
      //                eve: 20.65,
      //                morn: 11.17,
      //             },
      //             feels_like: {
      //                day: 22.49,
      //                night: 15.37,
      //                eve: 19.66,
      //                morn: 10.07,
      //             },
      //             pressure: 1023,
      //             humidity: 29,
      //             dew_point: 3.95,
      //             wind_speed: 1.66,
      //             wind_deg: 323,
      //             wind_gust: 2.14,
      //             weather: [
      //                {
      //                   id: 800,
      //                   main: "Clear",
      //                   description: "clear sky",
      //                   icon: "01d",
      //                },
      //             ],
      //             clouds: 0,
      //             pop: 0,
      //             uvi: 4.79,
      //          },
      //          {
      //             dt: 1696500000,
      //             sunrise: 1696480069,
      //             sunset: 1696521777,
      //             moonrise: 1696535340,
      //             moonset: 1696505160,
      //             moon_phase: 0.71,
      //             summary:
      //                "You can expect partly cloudy in the morning, with clearing in the afternoon",
      //             temp: {
      //                day: 23.41,
      //                min: 13.78,
      //                max: 24.66,
      //                night: 16.09,
      //                eve: 20.52,
      //                morn: 13.78,
      //             },
      //             feels_like: {
      //                day: 22.77,
      //                night: 15.43,
      //                eve: 19.72,
      //                morn: 12.91,
      //             },
      //             pressure: 1023,
      //             humidity: 37,
      //             dew_point: 7.6,
      //             wind_speed: 2.29,
      //             wind_deg: 331,
      //             wind_gust: 3.65,
      //             weather: [
      //                {
      //                   id: 802,
      //                   main: "Clouds",
      //                   description: "scattered clouds",
      //                   icon: "03d",
      //                },
      //             ],
      //             clouds: 37,
      //             pop: 0,
      //             uvi: 4.14,
      //          },
      //          {
      //             dt: 1696586400,
      //             sunrise: 1696566536,
      //             sunset: 1696608073,
      //             moonrise: 1696625220,
      //             moonset: 1696594800,
      //             moon_phase: 0.75,
      //             summary: "Expect a day of partly cloudy with clear spells",
      //             temp: {
      //                day: 21.31,
      //                min: 13.1,
      //                max: 23.49,
      //                night: 14.4,
      //                eve: 18.3,
      //                morn: 13.1,
      //             },
      //             feels_like: {
      //                day: 20.46,
      //                night: 12.99,
      //                eve: 17.05,
      //                morn: 12.24,
      //             },
      //             pressure: 1023,
      //             humidity: 37,
      //             dew_point: 5.62,
      //             wind_speed: 3.39,
      //             wind_deg: 14,
      //             wind_gust: 3.8,
      //             weather: [
      //                {
      //                   id: 804,
      //                   main: "Clouds",
      //                   description: "overcast clouds",
      //                   icon: "04d",
      //                },
      //             ],
      //             clouds: 100,
      //             pop: 0,
      //             uvi: 3.44,
      //          },
      //          {
      //             dt: 1696672800,
      //             sunrise: 1696653004,
      //             sunset: 1696694369,
      //             moonrise: 0,
      //             moonset: 1696683720,
      //             moon_phase: 0.77,
      //             summary:
      //                "The day will start with clear sky through the late morning hours, transitioning to partly cloudy",
      //             temp: {
      //                day: 19.29,
      //                min: 11.14,
      //                max: 22.06,
      //                night: 14.82,
      //                eve: 20.95,
      //                morn: 11.14,
      //             },
      //             feels_like: {
      //                day: 18.08,
      //                night: 13.3,
      //                eve: 19.73,
      //                morn: 9.8,
      //             },
      //             pressure: 1025,
      //             humidity: 31,
      //             dew_point: 1.13,
      //             wind_speed: 2.89,
      //             wind_deg: 325,
      //             wind_gust: 4.02,
      //             weather: [
      //                {
      //                   id: 803,
      //                   main: "Clouds",
      //                   description: "broken clouds",
      //                   icon: "04d",
      //                },
      //             ],
      //             clouds: 67,
      //             pop: 0,
      //             uvi: 3.35,
      //          },
      //          {
      //             dt: 1696759200,
      //             sunrise: 1696739471,
      //             sunset: 1696780666,
      //             moonrise: 1696715280,
      //             moonset: 1696772160,
      //             moon_phase: 0.8,
      //             summary:
      //                "The day will start with partly cloudy through the late morning hours, transitioning to clearing",
      //             temp: {
      //                day: 21.25,
      //                min: 11.05,
      //                max: 24.97,
      //                night: 17.84,
      //                eve: 23.95,
      //                morn: 11.05,
      //             },
      //             feels_like: {
      //                day: 20.11,
      //                night: 16.78,
      //                eve: 23.18,
      //                morn: 9.41,
      //             },
      //             pressure: 1021,
      //             humidity: 26,
      //             dew_point: 0.77,
      //             wind_speed: 4.12,
      //             wind_deg: 296,
      //             wind_gust: 6.49,
      //             weather: [
      //                {
      //                   id: 800,
      //                   main: "Clear",
      //                   description: "clear sky",
      //                   icon: "01d",
      //                },
      //             ],
      //             clouds: 7,
      //             pop: 0,
      //             uvi: 4.27,
      //          },
      //          {
      //             dt: 1696845600,
      //             sunrise: 1696825940,
      //             sunset: 1696866964,
      //             moonrise: 1696805580,
      //             moonset: 1696860240,
      //             moon_phase: 0.84,
      //             summary: "Expect a day of partly cloudy with clear spells",
      //             temp: {
      //                day: 20.25,
      //                min: 15.01,
      //                max: 22.09,
      //                night: 15.01,
      //                eve: 20.35,
      //                morn: 15.19,
      //             },
      //             feels_like: {
      //                day: 19.09,
      //                night: 13.69,
      //                eve: 19.2,
      //                morn: 14.1,
      //             },
      //             pressure: 1023,
      //             humidity: 29,
      //             dew_point: 1.5,
      //             wind_speed: 5.89,
      //             wind_deg: 307,
      //             wind_gust: 11.04,
      //             weather: [
      //                {
      //                   id: 801,
      //                   main: "Clouds",
      //                   description: "few clouds",
      //                   icon: "02d",
      //                },
      //             ],
      //             clouds: 11,
      //             pop: 0,
      //             uvi: 5,
      //          },
      //          {
      //             dt: 1696932000,
      //             sunrise: 1696912408,
      //             sunset: 1696953262,
      //             moonrise: 1696895820,
      //             moonset: 1696948020,
      //             moon_phase: 0.87,
      //             summary:
      //                "You can expect partly cloudy in the morning, with clearing in the afternoon",
      //             temp: {
      //                day: 21.11,
      //                min: 11.49,
      //                max: 24.93,
      //                night: 16.97,
      //                eve: 22.81,
      //                morn: 11.49,
      //             },
      //             feels_like: {
      //                day: 20.19,
      //                night: 16.03,
      //                eve: 21.98,
      //                morn: 10.1,
      //             },
      //             pressure: 1018,
      //             humidity: 35,
      //             dew_point: 4.58,
      //             wind_speed: 5.2,
      //             wind_deg: 307,
      //             wind_gust: 7.13,
      //             weather: [
      //                {
      //                   id: 804,
      //                   main: "Clouds",
      //                   description: "overcast clouds",
      //                   icon: "04d",
      //                },
      //             ],
      //             clouds: 100,
      //             pop: 0,
      //             uvi: 5,
      //          },
      //       ],
      //    },
      // };

      yield* put(
         weatherSlice.actions.setCurrentLocationForecast([
            {
               icon: currentLocationWeatherOneCall.data.current.weather[0].icon,
               temperature: {
                  min: Math.round(currentLocationWeatherOneCall.data.daily[0].temp.min),
                  current: Math.round(currentLocationWeatherOneCall.data.current.temp),
                  max: Math.round(currentLocationWeatherOneCall.data.daily[0].temp.max),
                  feelsLike: Math.round(
                     currentLocationWeatherOneCall.data.current.feels_like,
                  ),
               },
               description:
                  currentLocationWeatherOneCall.data.current.weather[0].description,
               summary: currentLocationWeatherOneCall.data.daily[0].summary,
               humidity: currentLocationWeatherOneCall.data.current.humidity,
               pressure: currentLocationWeatherOneCall.data.current.pressure,
               clouds: currentLocationWeatherOneCall.data.current.clouds,
               windSpeed: currentLocationWeatherOneCall.data.current.wind_speed,
               sunrise: currentLocationWeatherOneCall.data.current.sunrise,
               sunset: currentLocationWeatherOneCall.data.current.sunset,
               hourly: currentLocationWeatherOneCall.data.hourly.map((data: any) => ({
                  icon: data.weather[0].icon,
                  temperature: data.temp,
                  time: data.dt,
               })),
            },
            ...currentLocationWeatherOneCall.data.daily.slice(1).map((data: any) => {
               return {
                  icon: data.weather[0].icon,
                  temperature: {
                     min: Math.round(data.temp.min),
                     current: Math.round(data.temp.day),
                     max: Math.round(data.temp.max),
                     feelsLike: Math.round(data.feels_like.day),
                  },
                  description: data.weather[0].description,
                  summary: data.summary,
                  humidity: data.humidity,
                  pressure: data.pressure,
                  clouds: data.clouds,
                  windSpeed: data.wind_speed,
                  sunrise: data.sunrise,
                  sunset: data.sunset,
               };
            }),
         ]),
      );
   } catch (error) {
      console.log(error);

      yield* put(weatherSlice.actions.setCurrentLocationName(undefined));
      yield* put(weatherSlice.actions.setCurrentLocationForecast(undefined));
   }
}

function* weatherSaga() {
   yield* all([
      takeLatest(
         weatherSlice.actions.loadCurrentLocationForecast,
         onLoadCurrentLocationForecast,
      ),
   ]);
}

export default weatherSaga;
